# Generated by Django 5.2.4 on 2025-07-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('location_field', models.TextField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
