# Generated by Django 5.2.4 on 2025-07-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='english_level_required',
            field=models.CharField(blank=True, help_text='Required English level (e.g., B1, B2, C1)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_hybrid',
            field=models.BooleanField(default=False, help_text='Is the position hybrid?'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Is the position remote?'),
        ),
    ]
