# Generated by Django 5.2.4 on 2025-07-28 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_english_level_required_vacancy_is_hybrid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='english_level_required',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_hybrid',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_remote',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location_field',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NET', '.NET'), ('Account Manager', 'Account Manager'), ('AI/ML', 'AI/ML'), ('Analyst', 'Аналітик'), ('Android', 'Android'), ('Animator', 'Аніматор'), ('Architect', 'Архітектор'), ('Artist', 'Художник'), ('Assistant', 'Асистент'), ('Big Data', 'Big Data'), ('Blockchain', 'Блокчейн'), ('C++', 'C++'), ('C-level', 'C-level'), ('Copywriter', 'Копірайтер'), ('Data Engineer', 'Data Engineer'), ('Data Science', 'Data Science'), ('DBA', 'DBA'), ('Design', 'Дизайн'), ('DevOps', 'DevOps'), ('Embedded', 'Embedded'), ('Engineering Manager', 'Engineering Manager'), ('Erlang', 'Erlang'), ('ERP/CRM', 'ERP/CRM'), ('Finance', 'Фінанси'), ('Flutter', 'Flutter'), ('Front End', 'Front End'), ('Golang', 'Golang'), ('Hardware', 'Hardware'), ('HR', 'HR'), ('iOS/macOS', 'iOS/macOS'), ('Java', 'Java'), ('Legal', 'Юриспруденція'), ('Marketing', 'Маркетинг'), ('Node.js', 'Node.js'), ('Office Manager', 'Office Manager'), ('Other', 'Інше'), ('PHP', 'PHP'), ('Product Manager', 'Product Manager'), ('Project Manager', 'Project Manager'), ('Python', 'Python'), ('QA', 'QA'), ('React Native', 'React Native'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('Sales', 'Продажі'), ('Salesforce', 'Salesforce'), ('SAP', 'SAP'), ('Scala', 'Scala'), ('Scrum Master', 'Scrum Master'), ('Security', 'Безпека'), ('SEO', 'SEO'), ('Support', 'Підтримка'), ('SysAdmin', 'Сисадмін'), ('Technical Writer', 'Technical Writer'), ('Unity', 'Unity'), ('Unreal Engine', 'Unreal Engine')], max_length=50), default=['Other'], size=None, verbose_name='Категорії'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Kyiv', 'Київ'), ('Odessa', 'Одеса'), ('Kharkiv', 'Харків'), ('Dnepr', 'Дніпро'), ('Lviv', 'Львів'), ('Zaporizhzhia', 'Запоріжжя'), ('Kryvyi Rih', 'Кривий Ріг'), ('Mykolaiv', 'Миколаїв'), ('Mariupol', 'Маріуполь'), ('Lugansk', 'Луганськ'), ('Vinnytsia', 'Вінниця'), ('Simferopol', 'Сімферополь'), ('Sevastopol', 'Севастополь'), ('Khmelnytskyi', 'Хмельницький'), ('Chernihiv', 'Чернігів'), ('Cherkasy', 'Черкаси'), ('Sumy', 'Суми'), ('Rivne', 'Рівне'), ('Poltava', 'Полтава'), ('Kropyvnytskyi', 'Кропивницький'), ('Ternopil', 'Тернопіль'), ('Uzhhorod', 'Ужгород'), ('Lviv Region', 'Львівська область'), ('Ivano-Frankivsk', 'Івано-Франківськ'), ('Chernivtsi', 'Чернівці'), ('Remote', 'Віддалено')], max_length=50), blank=True, default=list, size=None, verbose_name='Міста'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('UA', 'Україна'), ('EU', 'Країни ЄС')], max_length=2), blank=True, default=list, size=None, verbose_name='Країни'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='custom_eu_cities',
            field=models.TextField(blank=True, null=True, verbose_name='Міста ЄС (вручну)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('UAH', '₴'), ('USD', '$'), ('EUR', '€')], max_length=3, null=True, verbose_name='Валюта зарплати'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна зарплата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мінімальна зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Опис вакансії'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Мови'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на вакансію'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name="Обов'язки"),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Навички'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва вакансії'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='tools',
            field=models.TextField(blank=True, null=True, verbose_name='Інструменти'),
        ),
    ]
