# Generated by Django 5.2.4 on 2025-08-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_remove_vacancy_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_hybrid',
            field=models.BooleanField(default=False, help_text='Чи є вакансія гібридною?'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Чи є вакансія віддаленою?'),
        ),
    ]
