# Generated by Django 5.2.4 on 2025-08-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_vacancy_is_hybrid_vacancy_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='english_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('NO_MATTER', 'Не має значення')], help_text='Необхідний рівень англійської', max_length=20),
        ),
    ]
