# Generated by Django 5.2.4 on 2025-08-14 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_alter_vacancy_english_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='tools',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name="Обов'язки"),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Навички'),
        ),
    ]
