# Generated by Django 5.2.4 on 2025-08-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_remove_vacancy_tools_alter_vacancy_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Рівень'),
        ),
    ]
