# Generated by Django 5.2.4 on 2025-08-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_vacancy_willing_to_relocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='custom_eu_cities',
        ),
    ]
