# Generated by Django 5.2.4 on 2025-08-14 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_remove_vacancy_custom_eu_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='willing_to_relocate',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Категорії'),
        ),
    ]
