# Generated by Django 5.2.4 on 2025-08-14 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0011_remove_vacancy_willing_to_relocate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='english_level',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Міста'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Країни'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Чи є вакансія повністю віддаленою?'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Рівень кандидата'),
        ),
    ]
