# Generated by Django 5.2.4 on 2025-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0012_remove_vacancy_english_level_alter_vacancy_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='languages',
            field=models.JSONField(blank=True, null=True, verbose_name='Мови'),
        ),
    ]
