# Generated by Django 5.2.4 on 2025-08-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0013_alter_vacancy_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_hybrid',
            field=models.BooleanField(default=False, help_text='Чи є вакансія гібридною?', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Чи є вакансія повністю віддаленою?', null=True),
        ),
    ]
