# Generated by Django 5.2.4 on 2025-08-20 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0014_alter_vacancy_is_hybrid_alter_vacancy_is_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Міста'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Країни'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None, verbose_name='Навички'),
        ),
    ]
