# Generated by Django 5.2.4 on 2025-09-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0015_remove_vacancy_responsibilities_alter_vacancy_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис вакансії'),
        ),
    ]
