# Generated by Django 5.2.4 on 2025-07-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Загальний відсоток співпадіння')),
                ('skills_match', models.FloatField(help_text='Відсоток співпадіння навичок')),
                ('tools_match', models.FloatField(help_text='Відсоток співпадіння інструментів')),
                ('responsibilities_match', models.FloatField(help_text="Відсоток співпадіння обов'язків")),
                ('languages_match', models.FloatField(help_text='Відсоток співпадіння мов')),
                ('location_match', models.FloatField(help_text='Відсоток співпадіння локації')),
                ('salary_match', models.FloatField(help_text='Відсоток співпадіння зарплати')),
                ('match_quality', models.CharField(help_text='Якість співпадіння (Low, Medium, High)', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='vacancy.vacancy')),
            ],
        ),
    ]
