# Generated by Django 5.2.4 on 2025-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='LinkedIn ID'),
        ),
    ]
