# Generated by Django 5.2.4 on 2025-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_languages_cv_location_field_cv_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='english_level',
            field=models.CharField(blank=True, help_text="User's English level (e.g., A1, A2, B1, B2, C1, C2)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='willing_to_relocate',
            field=models.BooleanField(default=False, help_text='Is the user willing to relocate?'),
        ),
    ]
