# Generated by Django 5.2.4 on 2025-08-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0003_cv_english_level_cv_willing_to_relocate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='location_field',
            new_name='location',
        ),
    ]
