# Generated by Django 5.2.4 on 2025-08-18 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0004_rename_location_field_cv_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='english_level',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='tools',
        ),
        migrations.AddField(
            model_name='cv',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='cv',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='cv',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_hybrid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_remote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='languages_detailed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills_detailed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='cv',
            name='willing_to_relocate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
