# Generated by Django 5.2.4 on 2025-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0005_remove_cv_english_level_remove_cv_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_office',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
