# Generated by Django 5.2.4 on 2025-08-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0006_cv_is_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='languages_detailed',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='skills_detailed',
            new_name='skills',
        ),
    ]
